/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Coders;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Namit
 */
public class Contribute extends javax.swing.JFrame {

    /**
     * Creates new form Contribute
     */
    String usname = null;
    public Contribute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(929, 775));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(118, 71, 177, 35);

        jTextField1.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(340, 72, 483, 43);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Question ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 194, 112, 34);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 194, 483, 413);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/newHome.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(850, 10, 50, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/newProfileback.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(-130, 0, 1040, 800);

        jTabbedPane1.addTab("Question", jPanel1);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Testcase 1");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(28, 25, 79, 22);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(130, 30, 241, 153);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Testcase 2");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(520, 25, 79, 22);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(652, 25, 240, 160);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Testcase 3");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(261, 254, 79, 22);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(381, 254, 254, 170);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Testcase 4");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 470, 79, 22);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(130, 470, 241, 167);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Testcase 5");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(530, 470, 79, 22);

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(650, 470, 241, 167);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/newProfileback.png"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(-100, -10, 1020, 840);

        jTabbedPane1.addTab("Testcase", jPanel2);

        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Output 1");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 20, 70, 30);

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea7.setRows(5);
        jScrollPane7.setViewportView(jTextArea7);

        jPanel3.add(jScrollPane7);
        jScrollPane7.setBounds(360, 250, 260, 165);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Output 2");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(510, 20, 70, 30);

        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea8.setRows(5);
        jScrollPane8.setViewportView(jTextArea8);

        jPanel3.add(jScrollPane8);
        jScrollPane8.setBounds(608, 24, 270, 165);

        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea9.setRows(5);
        jScrollPane9.setViewportView(jTextArea9);

        jPanel3.add(jScrollPane9);
        jScrollPane9.setBounds(114, 24, 260, 165);

        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea10.setRows(5);
        jScrollPane10.setViewportView(jTextArea10);

        jPanel3.add(jScrollPane10);
        jScrollPane10.setBounds(626, 488, 260, 165);

        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jTextArea11.setRows(5);
        jScrollPane11.setViewportView(jTextArea11);

        jPanel3.add(jScrollPane11);
        jScrollPane11.setBounds(120, 480, 260, 165);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Output 3");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(260, 250, 70, 30);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Output 4");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 490, 70, 30);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Output 5");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(536, 488, 70, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/newProfileback.png"))); // NOI18N
        jPanel3.add(jLabel17);
        jLabel17.setBounds(-100, -10, 1050, 840);

        jTabbedPane1.addTab("Required Outputs", jPanel3);

        jPanel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Solution");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(410, 40, 93, 34);

        jComboBox1.setBackground(new java.awt.Color(204, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "C++14", "Python2", "Python3" }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(694, 39, 110, 30);

        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Product Sans", 0, 24)); // NOI18N
        jTextArea12.setRows(5);
        jScrollPane12.setViewportView(jTextArea12);

        jPanel4.add(jScrollPane12);
        jScrollPane12.setBounds(88, 106, 716, 464);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Product Sans", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Make Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(370, 590, 180, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/newProfileback.png"))); // NOI18N
        jPanel4.add(jLabel18);
        jLabel18.setBounds(-130, 0, 1110, 820);

        jTabbedPane1.addTab("Solution", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        jLabel14.setBorder(null);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Homepage home = new Homepage();
        this.setVisible(false);
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection(JDBC_Connection.connectionAddress, JDBC_Connection.userName, JDBC_Connection.password);
                Statement stat = con.createStatement();

                String getUs = "SELECT username from Login_Logout";
                ResultSet rs = stat.executeQuery(getUs);
                while(rs.next())
                {
                    usname = rs.getString("username");
                }
                String insert = "INSERT INTO request_acess VALUES('"+ jTextField1.getText() + "',\""+ jTextArea1.getText() + "\",'" + Login.userrName + "',\"" + jTextArea12.getText() + "\",'" + jTextArea2.getText() + "','" + jTextArea3.getText() + "','" + jTextArea4.getText() + "','" + jTextArea5.getText() + "','" + jTextArea6.getText() +"','" + jTextArea7.getText() +"','" + jTextArea8.getText() +"','" +  jTextArea9.getText() +"','" + jTextArea10.getText() +"','" + jTextArea11.getText()+"','"+jComboBox1.getSelectedItem().toString()+"')";
                stat.executeUpdate(insert);

            
                stat.close();
                con.close();
            } catch (Exception e) {
                System.out.println("Exception caught --> " + e);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contribute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
