/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Coders;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Martand
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    String usname = null;
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Connection conne = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conne = DriverManager.getConnection(JDBC_Connection.connectionAddress, JDBC_Connection.userName, JDBC_Connection.password);
            Statement stat2 = conne.createStatement();
            String iString = "SELECT username FROM Login_Logout";
            System.out.println(iString);
            ResultSet rs2 = stat2.executeQuery(iString);
            while(rs2.next())
            {
                usname = rs2.getString("username");
            }
            usname = Login.userrName;
            stat2.close();
            conne.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
        }
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        practice = new javax.swing.JMenu();
        prepare = new javax.swing.JMenu();
        profile = new javax.swing.JMenu();
        contribute = new javax.swing.JMenu();
        settings = new javax.swing.JMenu();
        compiler = new javax.swing.JMenu();
        leaderboard = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 775));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Hola !");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 40, 150, 70);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText(usname);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 50, 240, 51);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/HomeBackgroungFinal.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-540, -140, 1550, 860);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 153));
        jMenuBar1.setFont(new java.awt.Font("Product Sans", 3, 18)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(0, 4));

        practice.setText("Practice");
        practice.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        practice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                practiceMouseClicked(evt);
            }
        });
        jMenuBar1.add(practice);

        prepare.setText("Prepare");
        prepare.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        prepare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prepareMouseClicked(evt);
            }
        });
        jMenuBar1.add(prepare);

        profile.setText("Profile");
        profile.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jMenuBar1.add(profile);

        contribute.setText("Contribute");
        contribute.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        contribute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contributeMouseClicked(evt);
            }
        });
        jMenuBar1.add(contribute);

        settings.setText("Settings");
        settings.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        jMenuBar1.add(settings);

        compiler.setText("Compiler");
        compiler.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        compiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compilerMouseClicked(evt);
            }
        });
        jMenuBar1.add(compiler);

        leaderboard.setText("Leaderboard");
        leaderboard.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        leaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaderboardMouseClicked(evt);
            }
        });
        jMenuBar1.add(leaderboard);

        logout.setText("Logout");
        logout.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void practiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_practiceMouseClicked
        // TODO add your handling code here:
        QuestionPage practicePage = new QuestionPage();
        this.setVisible(false);
        this.dispose();
        practicePage.setVisible(true);
    }//GEN-LAST:event_practiceMouseClicked

    private void prepareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prepareMouseClicked
        // TODO add your handling code here:
        Preparation prepare = new Preparation();
        this.setVisible(false);
        this.dispose();
        prepare.setVisible(true);
        
    }//GEN-LAST:event_prepareMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        Profile prof = new Profile();
        this.setVisible(false);
        this.dispose();
        prof.setVisible(true);
        
    }//GEN-LAST:event_profileMouseClicked

    private void contributeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contributeMouseClicked
        // TODO add your handling code here:
        Contribute contri = new Contribute();
        this.setVisible(false);
        this.dispose();
        contri.setVisible(true);
    }//GEN-LAST:event_contributeMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        // TODO add your handling code here:
        Settings set = new Settings();
        this.setVisible(false);
        this.dispose();
        set.setVisible(true);
    }//GEN-LAST:event_settingsMouseClicked

    private void compilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compilerMouseClicked
        // TODO add your handling code here:
        Compiler compile = new Compiler();
        this.setVisible(false);
        this.dispose();
        compile.setVisible(true);
    }//GEN-LAST:event_compilerMouseClicked

    private void leaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaderboardMouseClicked
        // TODO add your handling code here:
        LeaderBoard lb = new LeaderBoard();
        this.setVisible(false);
        this.dispose();
        lb.setVisible(true);
    }//GEN-LAST:event_leaderboardMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        CodersMain win = new CodersMain();
        this.setVisible(false);
        this.dispose();
        win.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu compiler;
    private javax.swing.JMenu contribute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu leaderboard;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu practice;
    private javax.swing.JMenu prepare;
    private javax.swing.JMenu profile;
    private javax.swing.JMenu settings;
    // End of variables declaration//GEN-END:variables
}
