/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Coders;

//import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.sql.*;
import javax.swing.JLabel;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Martand
 */
class LeaderBoardModel extends AbstractTableModel {

    @Override
    public int getRowCount() {
        return 0;
    }

    @Override
    public int getColumnCount() {
        return 0;
    }

    public Object getValueAt(int x, int y) {

        return null;
    }
}

public class LeaderBoard extends javax.swing.JFrame {

    int i = 0, count = 0;

    /**
     * Creates new form LeaderBoard
     */
    public LeaderBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int r,int c)
            {
                return false;
            }
            public Component prepareRenderer(TableCellRenderer r,int rw,int col)
            {
                Component c = super.prepareRenderer(r,rw,col);
                c.setBackground(Color.WHITE);
                //if(col==0)
                //{
                    c.setForeground(new Color(72,158,220));
                    //c.setForeground(new Color(255,255,255));
                    //}
                return c;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 775));
        setResizable(false);

        jPanel1.setLayout(null);

        jTable1.setModel(new LeaderBoardModel());
        jTable1.setFont(new java.awt.Font("Product Sans", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Position", "UserName", "Score"
            }
        ));
        jTable1.setRowHeight(32);
        jScrollPane1.setViewportView(jTable1);
        Connection con = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(JDBC_Connection.connectionAddress,JDBC_Connection.userName,JDBC_Connection.password);
            Statement stat3 = con.createStatement();
            Object data[][] = new Object[10][3];
            String in = "SELECT username,score FROM score ORDER BY score DESC";
            System.out.println(in);
            ResultSet rs = stat3.executeQuery(in);
            int j = 0;
            while(rs.next()){
                data[j][0] = j+1;
                data[j][1] = rs.getString("username");
                data[j][2] = rs.getString("score");
                j++;
            }
            DefaultTableModel model = new DefaultTableModel();
            String[] columns = {"Position","Username","Score"};
            model.setDataVector(data,columns);
            jTable1.setModel(model);
            stat3.close();
            con.close();
        } catch(Exception e){
            e.printStackTrace();
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(12, 102, 876, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/leadBack.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-100, 530, 1030, 290);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/leadbackround.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 70, 920, 530);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/leaderHomeIC.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(840, 10, 50, 50);

        jLabel4.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Homepage");
        jLabel4.setVisible(false);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(750, 30, 70, 18);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Leaderboard");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 30, 230, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/leadbackround.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 910, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.getTableHeader().setFont(new Font("Comic Sans MS", 3, 20));
        //jTable1.getTableHeader().setBackground(new Color(72,158,220));
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        //headerRenderer.setBackground(new Color(255, 255, 255));
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(headerRenderer);
        }
        //jTable1.getTableHeader().setForeground(new Color(72,158,220));
        JTableHeader head = jTable1.getTableHeader();
        head.setBackground(new Color(255,255,255));
        head.setForeground(new Color(72,158,220));
        ((DefaultTableCellRenderer)head.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Homepage home = new Homepage();
        this.setVisible(false);
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel4.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel4.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
