/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Coders;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
//import javax.swing.JOptionPane;

/**
 *
 * @author Namit
 */
public class Login extends javax.swing.JFrame {
    public static String userrName = "";
    static String userName;

    //static Login mainWindow;
    /**
     * ^
     * Creates new form Login
     */
    //private String usern,passn;
    boolean ret = false;

    public Login() {
        initComponents();
        //Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setSize(dim);
    }

//    public Login(String user, String pass)
//    {
//        usern  = user;
//        
//    }
//    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(900, 725));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("< Login >");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(610, 90, 180, 50);

        jLabel2.setFont(new java.awt.Font("Product Sans", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(561, 176, 120, 30);

        jLabel3.setFont(new java.awt.Font("Product Sans", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(561, 283, 110, 30);

        jTextField1.setFont(new java.awt.Font("Product Sans", 2, 18)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(560, 210, 290, 33);

        jPasswordField1.setFont(new java.awt.Font("Product Sans", 2, 18)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(560, 320, 290, 33);

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Product Sans", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 410, 120, 40);

        jLabel4.setFont(new java.awt.Font("Product Sans", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New User ? Sign Up Now");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 460, 155, 18);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/color3.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 60, 350, 580);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/homeICN.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 50, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/login_neww.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-270, -20, 1330, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        //Signup sign = new Signup();
        //loadPanel(sign);
        SignupJFrame win = new SignupJFrame();
        this.setVisible(false);
        this.dispose();
        win.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jLabel7.setBorder(null);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        CodersMain win = new CodersMain();
        this.setVisible(false);
        this.dispose();
        win.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JDBC_Connection connect = new JDBC_Connection();
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(connect.connect(), connect.getUsername(), connect.getPassword());
            //id1101599_db2         
            String insertString = "SELECT  username,password FROM user WHERE username = '" + jTextField1.getText() + "' " + "AND " + "password = '" + jPasswordField1.getText() + "'";
            userrName = jTextField1.getText();
            Statement stat = con.createStatement();
            //String insertString = "SELECT  username,password FROM user WHERE username = '" + jTextField1.getText() + "' " + "AND " + "password = '" + jPasswordField1.getText() + "'";
            System.out.println(insertString);
            ResultSet rs = stat.executeQuery(insertString);
            if (rs.next()) {
               // JOptionPane.showMessageDialog(null, "Login Successful");
                Connection conn = null;
		try
		{
			Class.forName("com.mysql.jdbc.Driver");
			conn = DriverManager.getConnection(JDBC_Connection.connectionAddress,JDBC_Connection.userName,JDBC_Connection.password);
			//id1101599_db2         
			Statement stat1 = conn.createStatement();
			String inString="INSERT INTO Login_Logout VALUES ('" + jTextField1.getText() + "')";
			System.out.println(inString);
			int rs1 = stat1.executeUpdate(inString);
			System.out.println("Return value from executeUpdate" + rs1);
			
			//con.commit();
                        //rs1.close();
			stat1.close();
			conn.close();
		}catch (Exception e)
		{
			System.out.println("Exception caught --> " + e);
		}
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Password");
//                Profile win = new Profile();
//                win.setjLabel5(jTextField1.getText());
                Homepage home = new Homepage();
                this.setVisible(false);
                this.dispose();
                home.setVisible(true);
                
               
            } else {
                jLabel3.setForeground(new java.awt.Color(255, 51, 51));
                jLabel3.setText("Invalid");
            }

            //con.commit();
            rs.close();
            stat.close();
            con.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBorder(null);
    }//GEN-LAST:event_jButton1MouseExited

//    public static void loadPanel(JPanel panel) {
//        Container container = mainWindow.getContentPane();
//        container.removeAll();
//        container.add(panel);
//        container.validate();
//        container.repaint();
//    }
//    public String saveUser() {
//            String save;
//            save = jTextField1.getText();
//            return save; //+ " " + jPasswordField1.getText();
//        
//       // return "No user";
//    }

    /**
     * @param args the command line arguments
     */
    // static Login Signup;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // mainWindow = new Login();
                new Login().setVisible(true);
                //mainWindow.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
