/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Coders;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Namit
 */
public class QuestionPage extends javax.swing.JFrame {

    /**
     * Creates new form QuestionPage
     */
    int value = 0; 
    int count = 0, i = 0;

    public QuestionPage() {
        initComponents();
    }

    public int getValue() {
        return value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int r,int c)
            {
                return false;
            }
            public Component prepareRenderer(TableCellRenderer r,int rw,int col)
            {
                Component c = super.prepareRenderer(r,rw,col);
                c.setBackground(Color.WHITE);
                //if(col==0)
                //{
                    c.setForeground(new Color(72,158,220));
                    //c.setForeground(new Color(255,255,255));
                    //}
                return c;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 775));
        setResizable(false);

        jPanel1.setLayout(null);

        jTable2.setFont(new java.awt.Font("Product Sans", 0, 24)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable2.setRowHeight(35);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 150, 831, 320);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Practice");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 40, 270, 67);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/practiceBack.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 480, 930, 390);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/praticeBackground.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 50, 940, 770);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/practiceHomeIC.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(840, 0, 50, 50);

        jLabel6.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setVisible(false);
        jLabel6.setText("Homepage");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(770, 20, 70, 18);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/praticeBackground.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 930, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Connection conne = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conne = DriverManager.getConnection(JDBC_Connection.connectionAddress, JDBC_Connection.userName, JDBC_Connection.password);
            Statement stat3 = conne.createStatement();
            String inString = "SELECT COUNT(*) FROM questions";
            System.out.println(inString);
            ResultSet rs3 = stat3.executeQuery(inString);
            while (rs3.next()) {
                count = rs3.getInt("COUNT(*)");
            }
            Object data[][] = new Object[count][3];
            Statement stat4 = conne.createStatement();
            String innString = "SELECT Question_Code,Question_Name,Question_Difficulty FROM questions";
            System.out.println(innString);
            ResultSet rs4 = stat4.executeQuery(innString);
            while (rs4.next()) {
                data[i][0] = rs4.getInt("Question_Code");
                data[i][1] = rs4.getString("Question_Name");
                data[i][2] = rs4.getString("Question_Difficulty");
                //data[i][3] = rs4.getInt("CPU_Time");
                i++;
            }
            DefaultTableModel model = new DefaultTableModel();
            String[] columnNames = {"Question_Code", "Question_Name", "Question_Difficulty"};
            model.setDataVector(data, columnNames);
            jTable2.setModel(model);
            //System.out.println("Return value from executeUpdate" + i);

            //con.commit();

            stat4.close();
            //stat2.close();
            stat3.close();
            conne.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
        }

        jTable2.getTableHeader().setFont(new Font("Comic Sans MS", 3, 20));
        //jTable1.getTableHeader().setBackground(new Color(72,158,220));
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        //headerRenderer.setBackground(new Color(255, 255, 255));
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int j = 0; j < jTable2.getModel().getColumnCount(); j++) {
            jTable2.getColumnModel().getColumn(j).setCellRenderer(headerRenderer);
        }
        //jTable1.getTableHeader().setForeground(new Color(72,158,220));
        JTableHeader head = jTable2.getTableHeader();
        head.setBackground(new Color(255,255,255));
        head.setForeground(new Color(72,158,220));
        ((DefaultTableCellRenderer)head.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        int column = jTable2.getSelectedColumn();
        value = (int) jTable2.getValueAt(row, 0);
        //System.out.println(value);
        Connection con = null;
        System.out.println(value);
        try {
            con = DriverManager.getConnection(JDBC_Connection.connectionAddress, JDBC_Connection.userName, JDBC_Connection.password);
            Statement stat3 = con.createStatement();
            String label = "", data = "";
            String instring = "SELECT Question_Name,Question FROM questions WHERE Question_Code = " + value;
            System.out.print(instring);
            ResultSet rs = stat3.executeQuery(instring);
            if (rs.next()) {
                label = rs.getString("Question_Name");
                data = rs.getString("Question");
            }
            stat3.close();
            con.close();
            this.setVisible(false);
            this.dispose();
            questionSee Qpage = new questionSee();
            Qpage.setjLabel1(label);
            Qpage.setjTextArea1(data);
            Qpage.setVisible(true);
        } catch (Exception f) {
            f.printStackTrace();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Homepage home = new Homepage();
        this.setVisible(false);
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jLabel6.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        jLabel6.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
