/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Coders;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Namit
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    String username = null;
    String pass;
    String email;
    String dob;
   // String type;

    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Connection conne = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conne = DriverManager.getConnection(JDBC_Connection.connectionAddress, JDBC_Connection.userName, JDBC_Connection.password);
            Statement stat2 = conne.createStatement();
            String iString = "SELECT username FROM Login_Logout";
            System.out.println(iString);
            ResultSet rs2 = stat2.executeQuery(iString);
            while(rs2.next())
            {
                username = rs2.getString("username");
            }
            username = Login.userrName;
            Statement stat4 = conne.createStatement();
            String innString = "SELECT password,email,Date_of_Birth FROM user WHERE username = '" + username +"'";
            System.out.println(innString);
            ResultSet rs4 = stat4.executeQuery(innString);
            while(rs4.next())
            {
                pass = rs4.getString("password");
                email = rs4.getString("email");
                dob = rs4.getString("Date_of_Birth");
                // type = rs4.getString("Type_of_User");
            }
            stat4.close();
            stat2.close();
            conne.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
        }
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/SettingsPerfect.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/SettingsPerfect.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings");
        setMinimumSize(new java.awt.Dimension(915, 767));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText(username);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 0, 320, 70);

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Product Sans", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Change Password");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(360, 250, 190, 40);

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Product Sans", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 153));
        jButton3.setText("Change Email");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(360, 320, 190, 40);

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Product Sans", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("Change Birthdate");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(360, 390, 190, 40);

        jButton5.setBackground(new java.awt.Color(204, 255, 255));
        jButton5.setFont(new java.awt.Font("Product Sans", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 153));
        jButton5.setText("Save Changes");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(430, 500, 181, 44);

        jButton7.setBackground(new java.awt.Color(204, 255, 255));
        jButton7.setFont(new java.awt.Font("Product Sans", 3, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setText("Delete Account");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(640, 500, 173, 44);

        jPasswordField1.setFont(new java.awt.Font("Product Sans", 2, 18)); // NOI18N
        jPasswordField1.setText(pass);
        jPasswordField1.setEditable(false);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(560, 250, 268, 40);

        jTextField2.setFont(new java.awt.Font("Product Sans", 2, 18)); // NOI18N
        jTextField2.setText(email);
        jTextField2.setEditable(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(560, 320, 268, 40);

        jTextField3.setFont(new java.awt.Font("Product Sans", 2, 18)); // NOI18N
        jTextField3.setText(dob);
        jTextField3.setEditable(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(560, 390, 268, 40);

        jLabel5.setFont(new java.awt.Font("Product Sans", 3, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Settings  ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 150, 440, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/SettingsPerfect.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-600, 60, 910, 590);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/setNew.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 310, 730);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/eye.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(840, 240, 102, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/seetingsHomeNew.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(850, 20, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/baacckkk.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 0, 610, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPasswordField1.setEditable(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField3.setEditable(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField2.setEditable(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Connection conne = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conne = DriverManager.getConnection(JDBC_Connection.connectionAddress, JDBC_Connection.userName, JDBC_Connection.password);
            //id1101599_db2         
            Statement stat2 = conne.createStatement();
            String iString = "UPDATE user SET password = '" + jPasswordField1.getText() + "', email = '" + jTextField2.getText() + "',Date_of_Birth = '" + jTextField3.getText() + "'" + " WHERE username = '" + Login.userrName + "'";
            System.out.println(iString);
            int rs2 = stat2.executeUpdate(iString);
            //rs2.close();
//            Statement stat3 = conne.createStatement();
//            String ss = "UPDATE Login_Logout SET username = '" + jTextField1.getText() + "'" + "WHERE username = '" + jLabel1.getText() + "'";
//            System.out.println(ss);
//            int rs3 = stat3.executeUpdate(ss);
            stat2.close();
            conne.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
        }
        Profile win = new Profile();
        this.setVisible(false);
        this.dispose();
        win.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBorder(null);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));

    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setBorder(null);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));

    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setBorder(null);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));

    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        jButton5.setBorder(null);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));

    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
        jButton7.setBorder(null);
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        // TODO add your handling code here:
        Connection conne = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conne = DriverManager.getConnection(JDBC_Connection.connectionAddress, JDBC_Connection.userName, JDBC_Connection.password);
            //id1101599_db2         
            
            Statement stat3 = conne.createStatement();
            String inString = "DELETE FROM score WHERE username = '" + username + "'";
            System.out.println(inString);
            int rs3 = stat3.executeUpdate(inString);
            Statement stat4 = conne.createStatement();
            String innString = "DELETE FROM submissions WHERE username = '" + username + "'";
            System.out.println(innString);
            int rs4 = stat4.executeUpdate(innString);
            Statement stat5 = conne.createStatement();
            String innnString = "DELETE FROM Login_Logout WHERE username = '" + username + "'";
            System.out.println(innnString);
            int rs5 = stat5.executeUpdate(innnString);
            Statement stat2 = conne.createStatement();
            String iString = "DELETE FROM user WHERE username = '" + username + "'";
            System.out.println(iString);
            int rs2 = stat2.executeUpdate(iString);
            stat3.close();
            stat4.close();
            stat5.close();
            stat2.close();
            conne.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
        }
        CodersMain win = new CodersMain();
        this.setVisible(false);
        this.dispose();
        win.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jPasswordField1.setEchoChar((char) 0);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Homepage home = new Homepage();
        this.setVisible(false);
        this.dispose();
        home.setVisible(true);
        
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
