/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Coders;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
//import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Namit
 */
public class Testing extends javax.swing.JFrame {

    /**
     * Creates new form Testing
     */
    String username = null;
    int count = 0,i=0;
    public Testing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int r,int c)
            {
                return false;
            }
            public Component prepareRenderer(TableCellRenderer r,int rw,int col)
            {
                Component c = super.prepareRenderer(r,rw,col);
                c.setBackground(Color.WHITE);
                //if(col==0)
                //{
                    c.setForeground(new Color(72,158,220));
                    //c.setForeground(new Color(255,255,255));
                    //}
                return c;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(915, 767));
        setResizable(false);

        jPanel1.setLayout(null);

        jTable1.setFont(new java.awt.Font("Product Sans", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(34, 251, 839, 180);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Submissions History");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 170, 380, 44);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 110, 227, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/backSub.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(830, 20, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images OOP Project/HistoryBack.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-480, -10, 1450, 980);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );

        Connection conne = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conne = DriverManager.getConnection(JDBC_Connection.connectionAddress, JDBC_Connection.userName, JDBC_Connection.password);
            //id1101599_db2
            Statement stat2 = conne.createStatement();
            String iString = "SELECT username FROM Login_Logout";
            System.out.println(iString);
            ResultSet rs2 = stat2.executeQuery(iString);
            while(rs2.next())
            {
                username = rs2.getString("username");
            }
            username = Login.userrName;
            Statement stat3 = conne.createStatement();
            String inString = "SELECT COUNT(*) FROM submissions WHERE username = '" + username + "'";
            System.out.println(inString);
            ResultSet rs3 = stat3.executeQuery(inString);
            while(rs3.next())
            {
                count = rs3.getInt("COUNT(*)");
            }
            Object data[][] = new Object[count][5];
            Statement stat4 = conne.createStatement();
            String innString = "SELECT Question_Code,Status,Memory,CPU_Time,Language FROM submissions WHERE username = '" + username +"'";
            System.out.println(innString);
            ResultSet rs4 = stat4.executeQuery(innString);
            while(rs4.next())
            {
                data[i][0] = rs4.getInt("Question_Code");
                data[i][1] = rs4.getString("Status");
                data[i][2] = rs4.getInt("Memory");
                data[i][3] = rs4.getInt("CPU_Time");
                data[i][4] = rs4.getString("Language");
                i++;
            }
            DefaultTableModel model = new DefaultTableModel();
            String[] columnNames = {"Question Code","Status","Memory","CPU Time","Language"};
            model.setDataVector(data,columnNames);
            jTable1.setModel(model);
            //System.out.println("Return value from executeUpdate" + i);

            //con.commit();

            stat4.close();
            stat2.close();
            stat3.close();
            conne.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
        }

        jLabel2.setText(username);
        jTable1.getTableHeader().setFont(new Font("Comic Sans MS", 3, 20));
        //jTable1.getTableHeader().setBackground(new Color(72,158,220));
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        //headerRenderer.setBackground(new Color(255, 255, 255));
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(headerRenderer);
        }
        //jTable1.getTableHeader().setForeground(new Color(72,158,220));
        JTableHeader head = jTable1.getTableHeader();
        head.setBackground(new Color(255,255,255));
        head.setForeground(new Color(72,158,220));
        ((DefaultTableCellRenderer)head.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Profile win = new Profile();
        this.setVisible(false);
        this.dispose();
        win.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setBorder(null);
    }//GEN-LAST:event_jLabel3MouseExited
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
